-d C:\Users\gusta\OneDrive\Documentos\Novos_projetos_HDL\dc_motor_control\impl\gwsynthesis\dc_motor_control.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\gusta\OneDrive\Documentos\Novos_projetos_HDL\dc_motor_control\src\dc_motor_control.cst
-cfg C:\Users\gusta\OneDrive\Documentos\Novos_projetos_HDL\dc_motor_control\impl\pnr\device.cfg
-bit
-tr
-ph
-warning_all
-timing
-cst_error
-route_maxfan 23
